/*
 * Sogang Univ, Graphics Lab, 2024
 * 
 * Vulkan Full Raytracing
 * 
 */

#version 460

#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "geometrytypes.glsl"
#include "bufferreferences.glsl"

hitAttributeEXT vec2 attribs;
layout(location = 1) rayPayloadInEXT uint payloadSeed;

layout(binding = 2, set = 0) uniform uniformBuffer
{
	mat4 viewInverse;
	mat4 projInverse;
	vec4 lightPos[1];
} ubo;

layout(binding = 3, set = 0) uniform sampler2D image;
layout(binding = 4, set = 0) buffer GeometryNodes { GeometryNode nodes[]; } geometryNodes;
layout(binding = 6, set = 0) uniform sampler2D textures[];

#include "geometryfunctions.glsl"
#include "random.glsl"

void main()
{
	Triangle tri = unpackTriangle(gl_PrimitiveID, 112);
	GeometryNode geometryNode = geometryNodes.nodes[nonuniformEXT(gl_GeometryIndexEXT)];

	vec4 color = texture(textures[nonuniformEXT(geometryNode.textureIndexBaseColor)], tri.uv);

	if(color.a == 0.0f) {
		ignoreIntersectionEXT;
	}
}