/*
 * Sogang University
 *
 * Graphics Lab, 2024
 *
 */

#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_nonuniform_qualifier : require

#include "random.glsl"
#include "geometrytypes.glsl"
#include "../base/light.glsl"
#include "../base/pbr.glsl"

struct RayPayload {
	vec3 color;
	float distance;
	vec3 normal;
	uint objectID;
	vec3 albedo;	
	float metallic;	
};
layout(location = 0) rayPayloadEXT RayPayload rayPayload;
layout(location = 1) rayPayloadEXT uint payloadSeed;
layout(location = 2) rayPayloadEXT bool shadowed;

layout(binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, rgba8) uniform image2D image;
layout(binding = 2) buffer GeometryNodes { GeometryNode nodes[]; } geometryNodes;
layout(binding = 3) uniform uniformBuffer
{
	mat4 viewInverse;
	mat4 projInverse;
	mat4 lightSpace;
	uint frame;
	vec4 lightPos;
} ubo;
layout(binding = 4) uniform sampler2D posSampler;
layout(binding = 5) uniform sampler2D normSampler;
layout(binding = 6) uniform sampler2D albedoSampler;
layout(binding = 7) uniform sampler2D metallicRoughSampler;
layout(binding = 8) uniform sampler2D emisSampler;
layout(binding = 9) uniform samplerCube samplerColor;
layout(binding = 10) uniform sampler2D shadowMap;
layout(binding = 11) uniform sampler2D lightMap;
layout(binding = 12) uniform sampler2D textures[];

#define amb 0.1

float LinearizeDepth(float depth)
{
//  float n = 1.0f;
//  float f = 500.0f;

    float n = 0.1f;
  float f = 100.0f;

  float z = depth;
  return (2.0 * n) / (f + n - z * (f - n));	
}

void main() 
{
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);	// pixel position
	const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);	// pixel position in WdC
	vec2 d = inUV * 2.0f - 1.0f;	// pixel position in NDC
	
	vec4 originPos = texture(posSampler, inUV).xyzw;
	vec3 pos = originPos.xyz;
	uint objectID = uint(round(originPos.w));

	if (objectID-- == 0)
    {
        vec4 origin = ubo.viewInverse * vec4(0.0f, 0.0f, 0.0f, 1.0f);
        vec4 target = ubo.projInverse * vec4(d.x, d.y, 1.0f, 1.0f) ;    // (pixel position in EC) / Wc
        vec3 direction = normalize(ubo.viewInverse * vec4(normalize(target.xyz), 0.0f)).xyz;
        vec3 envColor = textureLod(samplerColor, direction, 0.0).rgb;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(envColor, 1.0f));
        return;
    }

	vec3 albedo = pow(texture(albedoSampler, inUV).rgb, vec3(2.2));

	vec3 aometallicRoughness = texture(metallicRoughSampler, inUV).rgb;
	float ao = aometallicRoughness.r;
	float roughness = aometallicRoughness.g;
	float metallic = aometallicRoughness.b;

	vec3 emissive = texture(emisSampler, inUV).rgb;

	vec3 N = texture(normSampler, inUV).xyz;

	vec3 V = normalize((ubo.viewInverse * vec4(0.0f, 0.0f, 0.0f, 1.0f)).xyz - pos);

	int numOfLights = NUM_OF_LIGHTS;

	GeometryNode geometryNode = geometryNodes.nodes[objectID];
	float ior = geometryNode.ior;
	vec3 F0 = vec3(pow((ior - 1)/(ior + 1), 2));
	F0 = mix(F0, albedo, metallic);

	vec3 pbrColor = vec3(0.0f);
	float shadow = 0.0f;
	// Local Shading Part
	{
		vec3 Lo = vec3(0.0f);
		shadow = texture(lightMap, inUV).r;
		float shadowEdge = texture(shadowMap, inUV).r;

		if (shadowEdge > 0.5f)
		{
			shadowed = true;
			vec3 rayDirection = ubo.lightPos.xyz - originPos.xyz;
			float tmin = 0.1f;
			float tmax = length(rayDirection);
			rayDirection = normalize(rayDirection);
			traceRayEXT(topLevelAS, gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT, 0xff, 0, 0, 1, originPos.xyz + N * 0.01f, tmin, rayDirection.xyz, tmax, 2);
			if (shadowed)
				shadow = 1.0f;
		}

		if (shadow == 0.0f) {
			vec3 L = normalize(ubo.lightPos.xyz - pos);

			vec3 H = normalize(V + L);

			vec3 radiance = lightInfo.color;

			float NDF = DistributionGGX(N, H, roughness);
			float G   = GeometrySmith(N, V, L, roughness);      
			vec3 F    = FresnelSchlick(max(dot(H, V), 0.0), F0);
           
			vec3 numerator    = NDF * G * F; 
			float denominator = 4.0 * max(dot(N, V), 0.0) * max(dot(N, L), 0.0) + 0.0001; 
			vec3 specular = numerator / denominator;
        
			vec3 kS = F;

			vec3 kD = vec3(1.0) - kS;

			kD *= 1.0 - metallic;	  

			float NdotL = max(dot(N, L), 0.0);        

			Lo += (kD * albedo / PI + specular) * radiance * NdotL;
		}	
	
		vec3 ambient = vec3(0.05f) * albedo;

		pbrColor = ambient + emissive + Lo;
	}

	pbrColor = pow(pbrColor, vec3(1.0f / 2.2f));

	//pbrColor = vec3(1.0f - texture(shadowMap, inUV).r);

	//pbrColor = vec3(1.0f - texture(lightMap, inUV).r);

	//pbrColor = vec3(texture(shadowMap, inUV).r);

	//pbrColor = texture(lightMap, inUV).rgb;

	imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(pbrColor, 1.0f));	// write a single texel into an image.
}